server.address=0.0.0.0
server.port=${PORT:7860}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB

server.forward-headers-strategy=framework
app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}

face.service.url=${FACE_SERVICE_URL}
upload.dir=${UPLOAD_DIR:/tmp/uploads}
